name: Test, Build and Deploy app

on:
  push:
    branches: [ "main" ]

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build a Docker image
        run: docker build -t test-image .
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: test-image
          args: --severity-threshold=high --file=Dockerfile
  
  build:
    needs: snyk-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and tag Docker image
      run: |
        docker build . --file Dockerfile -t agotfrid/python-app:latest -t agotfrid/python-app:${{ github.sha }}
        docker push agotfrid/python-app:latest
        docker push agotfrid/python-app:${{ github.sha }}
   
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'Agotfrid/kustomize-example'
        token: ${{ secrets.KUSTOMIZE_REPO_ACCESS_TOKEN }}

    - name: Update image tag in Kustomization
      run: |
        export IMAGE_VERSION=${{ github.sha }}
        envsubst < overlays/develop/kustomization.template.yaml > overlays/develop/kustomization.yaml
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Update image version to ${{ github.sha }}"
        git push
